### ISSUE TITLE
attachListener/rendition2.js has wrong 'this' value and leaks memory

### ISSUE THREAD

**Issue by mstetson** [david-mark/jessie#266]
In an attempt to work around memory leaks in very old versions of IE, attachListener/rendition2.js stores a reference to the element in jessieNamespace.theseObjects for use as 'this' in the listener and then nulls the passed-in element variable. But the listener actually uses the passed-in element variable rather than the stored reference, so 'this' is always null in the callback.

If that is fixed, though, there is still no function in jessie that removes element references from jessieNamespace.theseObjects. That means no DOM elements used with attachListener/rendition2.js will be garbage collected while the page is open. So a test like this leaks memory:

```javascript
var i, el, fn;
for (i = 0; i < 50000; i++) {
	el = document.createElement("div");
	el.innerHTML = "fill in with 1k of text so you notice the leak in task manager";
	fn = jessie.attachListener(el, 'click', function (event) {});
	jessie.detachListener(el, 'click', fn);
}
```

The following rendition does not leak with the above test in IE8.

```javascript
attachListener = function (el, eventType, fn) {
	var listener = function () {
		fn.call(el, window.event);
	}
	el.attachEvent('on' + eventType, listener);
	return listener;
};
```

It may be worthwhile to offer a rendition for ancient IE that stores the 'this' value outside the closure, so long as there's a way to clean those up when discarding DOM elements.

**Comment by david-mark** [comment]
Storing it in theseObjects does put it outside the closure. That's the point of that. I fixed the obvious typo where it is passing null instead of the stashed element reference.

Your leak test introduces additional variables. It is supposed to be testing attaching listeners, not creating elements or the innerHTML property. Shouldn't be detaching any listeners either. If you attach and then detach, barring any other variables, the net is 0.

You shouldn't have to clean up the listeners at all, that's the point of avoiding the circular reference by storing the element reference outside the closure. It's the same thing My Library does and it was leak-tested to death (with and without the unneeded IE-specific cleanup code) in all of the old IE versions.

So you should write the test without removing any listeners at all. Just refresh the page after each run. If the memory keeps going up (all things equal), then there's a leak.

The reason that last rendition you posted doesn't "leak" is that you are simply removing the listeners as fast as you add them. If you test properly (without detaching listeners at all), you'll find it does leak as it creates the classic circular reference.

http://jibbering.com/faq/notes/closures/#clMem

**Comment by david-mark** [comment]
And thanks for spotting that typo in Rendition #2. :)

**Comment by david-mark** [comment]
Rendition #3 had copied over the same typo. Fixed.

**Comment by david-mark** [comment]
Summary:

Leaked memory cannot be reclaimed without *restarting* the browser. If you meticulously detach all attached listeners, then you don't need the leak management as found in Rendition #2 and #3. In fact, you could use the rendition posted, creating circular references on attach and breaking them on detach.

Context is always important. If writing a "single page app" and planning to attach and detach listeners repeatedly (usually sign of a bad design), and particularly if attaching to newly created (or cloned) elements each time, it should be clear that, if using #2 or #3 in old IE versions, the length of - theseElements - will increase each time and memory usage will go up until the page is refreshed (at which time the GC will reclaim the memory that appeared to leak).

**Comment by mstetson** [comment]
I agree that the leak demonstrated in my test is not likely to cause actual problems in most well-designed systems. But renditions 2 and 3 are only creating ``theseObjects``` to work around bugs in browser versions that my customers don't use. Looking at the rendition, it irked me to think of introducing a potential resource leak for my IE 8 users in an attempt to accommodate non-existent IE 7 users.

This really points out a great feature of the Jessie approach: rather than simply taking the library code as a black box, I'm prompted to consider which renditions to include and think about the consequences of each. Thanks for that. It would be nice if more of the "why use this rendition?" arguments were available directly in the builder.

**Comment by david-mark** [comment]
"I agree that the leak demonstrated in my test is not likely to cause actual problems in most well-designed systems."

Pseudo leak. Real leaks don't come back, even when navigating (e.g. to a login page) or refreshing.

"But renditions 2 and 3 are only creating theseObjects to work around bugs in browser versions that my customers don't use."

Right. So those shouldn't be your first choice.

"Thanks for that. It would be nice if more of the "why use this rendition?" arguments were available directly in the builder."

You're welcome. Code comments welcome. Each rendition should have a blurb at the top explaining its positives and negatives. Don't recall what the builder does (haven't seen it in years). Started working on my own version of it years ago, but other things have come up since.
